version: '3'
services:
  mongo:
    image: "mongo:5.0.5"
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydb

  jupyter:
    depends_on: 
      - mongo 
    image: jupyter/base-notebook 
    restart: always
    ports:
      - "8888:8888"
    expose:
      - "8888"
    volumes:
      - ./:/home/jovyan/work 
    links:
      - "mongo:mongo"              

  backend:
    depends_on: 
      - mongo  
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    expose:
      - "3000" 
    links:
      - "mongo:mongo"
    environment:
      MONGODB_URL: mongodb://root:example@mongo:27017/admin


  frontend:
    depends_on: 
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - backendURL=http://localhost:3000
    restart: always
    ports:
      - "80:80"
    expose:
      - "80"



      